apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Application
      name: ngo-service
    patch: |-
      - op: replace
        path: /spec/source/path
        value: gitops/workloads/overlays/dr/ngo-service
  - target:
      kind: Application
      name: donation-service
    patch: |-
      - op: replace
        path: /spec/source/path
        value: gitops/workloads/overlays/dr/donation-service
  - target:
      kind: Application
      name: volunteer-service
    patch: |-
      - op: replace
        path: /spec/source/path
        value: gitops/workloads/overlays/dr/volunteer-service
