apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
- ../../../base/donation-service
images:
- name: donation-service
  newName: 712819938659.dkr.ecr.us-east-1.amazonaws.com/solidarytech/donation-service
  newTag: 3170bcde7f11b13bdb21115ecd83c06ee107b149
