apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
- ../../../base/donation-service
images:
- name: donation-service
  newName: 712819938659.dkr.ecr.us-east-1.amazonaws.com/solidarytech/donation-service
  newTag: 7504328f4518bc14129ef891462d537e6d0e6c3f
