apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
- ../../../base/donation-service
images:
- name: donation-service
  newName: 712819938659.dkr.ecr.us-east-1.amazonaws.com/solidarytech/donation-service
  newTag: 078f33633e161c333270d13f54680d8bcdee3c60
