apiVersion: v1
kind: Service
metadata:
  name: donation-service
  labels:
    app.kubernetes.io/name: donation-service
spec:
  selector:
    app.kubernetes.io/name: donation-service
  ports:
    - name: http
      port: 8082
      targetPort: http
