apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solidarytech
resources:
  - ../../../base/volunteer-service
images:
  - name: volunteer-service
    newName: 712819938659.dkr.ecr.us-east-2.amazonaws.com/solidarytech/volunteer-service
    newTag: latest
patches:
  - target:
      kind: ServiceAccount
      name: volunteer-service
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::712819938659:role/solidarytech-dr-volunteer-service
